name: sgc
description: Sistema SGC Mobile
publish_to: 'none'
version: 1.5.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  loading_animation_widget: ^1.2.0+4
  flutter_speed_dial: ^7.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  http: ^1.2.2
  intl: ^0.20.1
  flutter_bloc: ^8.1.4
  flutter_slidable: ^3.0.1
  flutter_advanced_drawer: ^1.3.6
  flutter_secure_storage: ^9.0.0
  flutter_local_notifications: ^18.0.1
  package_info_plus: ^8.1.0
  version: ^3.0.2
  camera: ^0.11.0+2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family : Poppins
      fonts: 
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
